[workspace]

members = [
  "engine",
  "oracle",
  "xtask",
  "oracle_feed_demo",
  "user_pallet",
]

[workspace.package]
version = "0.1.0"
edition = "2021"




[workspace.dependencies]

anyhow = "1"
console = "0.15"

serde = { version = "1.0", features = ["derive"]}

bincode = "1.3.3"

