[package]
name = "xtask"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


anyhow = { workspace = true }
console = { workspace = true }

clap = { version = "4", features = ["derive"] }
duct = "0.13"
